#+STARTUP: overview
#+TITLE: Ejercicios JS
#+LANGUAGE: es
#+OPTIONS: num:nil
#+ATTR_HTML: :style margin-left: auto; margin-right: auto;
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

* Ejercicio 1
  Crear un arreglo llamado meses y que almacene el nombre de los 12
  meses del año.

  Utilizando console.log muestre los 12 meses utilizando
  una función.
** Respuesta
   #+begin_src js :tangle Ejercicio1.js
     let meses = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'];

     console.log(meses);
   #+end_src
* Ejercicio 2
  Utilizando el siguiente arreglo:
  =let valores = [true, 5, false, “hola”,“adios”, 2];=

  - Determinar cuál de los dos elementos de texto es mayor.
** Respuesta
   #+begin_src js :tangle Ejercicio2.js
      let valores = [true, 5, false, 'hola', 'adios', 2];
      let str1 = valores[3].length;
      let str2 = valores[4].length;
      let mayor;

      if( str1 > str2 ){
          mayor = valores[3];
      }

      if( str1 < str2) {
          mayor = valores[4];
      }

      if( str1 == str2) {
          mayor = 'ninguno.';
      }

      console.log('el elemento de texto mayor es:', mayor );
   #+end_src

   #+RESULTS:
   : el elemento de texto mayor es: adios
   : undefined

* Ejercicio 3
** Indicacion
   Completar las condiciones del siguiente código para que los mensajes
   se muestren de manera correcta
   #+begin_src js
     let numero1 = 5;
     let numero2 = 8;
     if(...)
     {
     console.log("número 1 no es mayor que número 2");
     }
     if(...)
     {
     console.log("número 2 es positivo");
     }
     if(...)
     {
     console.log("número 1 es negativo o distinto de cero");
     }
     if(...)
     {
     console.log("Incrementar en 1 unidad el valor del número 1 no lo
     hace mayor que el número 2");
     }
   #+end_src
** Respuesta
   #+begin_src js :tangle Ejercicio3.js
     let numero1 = 5;
     let numero2 = 8;

     if( numero1 <= numero2)
     {
         console.log("número 1 no es mayor que número 2");
     }
     if( numero1 >= 0 )
     {
         console.log("número 2 es positivo");
     }
     if( numero1 < 0 )
     {
         console.log("número 1 es negativo o distinto de cero");
     }
     if( (numero1 + 1) <= numero2 )
     {
         console.log("Incrementar en 1 unidad el valor del número 1 no lo hace mayor que el número 2");
     }
   #+end_src

 #+RESULTS:
 : número 1 no es mayor que número 2
 : número 2 es positivo
 : Incrementar en 1 unidad el valor del número 1 no lo hace mayor que el número 2
 : undefined
* Ejercicio 4
  El factorial de un número entero n es una operación matemática que
  consiste en multiplicar todos los factores

  =n x (n -1) x (n-2) x … x 1.=

  Así el factorial de 5 (escrito como ~5!~) es igual a:

  =5! = 5 x 4 x 3 x 2 x 1 = 120.=

  Utilizando funciones y la estructura for, cree un script que calcule
  el factorial de un número entero.
** Respuesta
   #+begin_src js :tangle Ejercicio4.js
     function factorial( num ) {
         let result = num;

         for (let i = 1; num > i; i++){
             result *= i;
         }

         return result;
     }

     let userInput;
     let result;

     userInput = prompt('Introduzca un numero');

     output = factorial(userInput);
     console.log(output);
   #+end_src

   #+RESULTS:
   : 120
   : undefined

* Ejercicio 5
  Escriba una función que reciba una cadena de texto y muestre como
  resultado si la cadena de texto está compuesta por letras mayúsculas
  o letras minúsculas
** Respuesta
   #+begin_src js :tangle Ejercicio5.js
     function whichCase ( string ){
         let result;

         if( string == string.toUpperCase() ){
             result = 'Mayúsculas';
             return result;
         }

         if( string == string.toLowerCase() ){
             result = 'Minúsculas';
             return result;
         }

         return result = 'Ambos';
     }

     let userInput;
     let output;

     userInput = prompt('Introduzca un texto');

     output = whichCase(userInput);
     console.log('El texto esta compuesta por:', output);
   #+end_src

   #+RESULTS:
   : Ambos
   : undefined

* Ejercicio 6
  Escriba una función que reciba un número y diga si este número es
  par o impar.
** Respuesta
   #+begin_src js :tangle Ejercicio6.js
     function isPair ( num ) {

         if( num % 2 == 0){
             return 'Par';
         }

         return 'Impar';
     }

     let userInput;
     let output;

     userInput = prompt('Introduzca un numero');

     output = isPair(userInput);
     console.log('El numero es:', output);
   #+end_src

   #+RESULTS:
   : El numero es: Impar
   : undefined

* Ejercicio 7
  Escriba una función que reciba un número y diga si este es primo o
  no
** Respuesta
   #+begin_src js :tangle Ejercicio7.js
     function isPrime( num ) {
         let result;
         num <= 1 ? result = false : result = true;

         for ( let i = 2; num > i; i++ ) {
             if ( num % i == 0 ) { result = false; }
         }

         result == true ? result = 'primo' : result = 'no primo';

         return result;
     }

     userInput = prompt('Introduzca un numero');

     output = isPrime(userInput);
     console.log('El numero es:', output);
   #+end_src

   #+RESULTS:
   : El numero es: no primo
   : undefined

* Ejercicio 8
  Cree un arreglo de alumno (nombre, edad, claseCursa) que contenga 10
  elementos y realice lo siguiente:
  - Utilizando la función filter muestre los estudiantes mayores de 18
    años y menores de 25
  - Utilizando la función find muestre al estudiante que tenga 20
    años.
  - Utilizando la función reduce agregue en un nuevo arreglo a los
    estudiantes que tienen entre 20 y 22 años de edad.
** Respuesta
   #+begin_src js :tangle Ejercicio8.js
     function jovenAdulto( edadMenor, edadMayor, alumno ){
         let resultado;

         resultado = alumno.filter( alumno => ( alumno.edad > edadMenor &&
                                                alumno.edad < edadMayor ) );

         return resultado;
     }

     function dosDecadas( edad, alumno ){
         let resultado;
         resultado = alumno.find(alumno => alumno.edad === 20);

         return resultado;
     }

     function filtrarAlumnos( edadMenor, edadMayor, alumno ){
         let resultado;
         let isAgeRange = false;

         resultado = alumno.reduce((acumulador, valorActual) => {

             const llave = valorActual['edad'];
             isAgeRange = llave >= edadMenor && llave <= edadMayor;
             if (!isAgeRange) { return acumulador; }

             const valor = acumulador[llave] ? [...acumulador[llave], valorActual ] : [valorActual];

             acumulador[llave] = valor;
             return acumulador;

         }, {}
                                  );

         return resultado;
     }

     let alumno = [
         {
             nombre: 'Dewayne Damon',
             edad: 20,
             claseCursa: 'Filosofia'
         },

         {
             nombre: 'Brevyn Malik',
             edad: 26,
             claseCursa: 'Diseno de Base de Datos'
         },

         {
             nombre: 'Jarrett Brayden',
             edad: 27,
             claseCursa: 'Validacion y Mantenimiento de Software'
         },

         {
             nombre: 'Maia Katelynn',
             edad: 17,
             claseCursa: 'Programacion 1'
         },

         {
             nombre: 'Sebestian Sanjay',
             edad: 24,
             claseCursa: 'Metodologia de la Investigacion'
         },

         {
             nombre: 'Lindsey Roselle',
             edad: 19,
             claseCursa: 'Marketing'
         },

         {
             nombre: 'Dane Baylor',
             edad: 22,
             claseCursa: 'Muricion'
         },

         {
             nombre: 'Alina Jayne',
             edad: 21,
             claseCursa: 'Calculo Diferencial'
         },

         {
             nombre: 'Trixy Aurelia',
             edad: 18,
             claseCursa: 'Sistemas Distribuidos'
         },

         {
             nombre: 'Billy Rodrigo',
             edad: 23,
             claseCursa: 'Filosofia'
         },

         {
             nombre: 'Kiran Klay',
             edad: 18,
             claseCursa: 'Diseno de Base de Datos'
         },

         {
             nombre: 'Pat Reef',
             edad: 22,
             claseCursa: 'Validacion y Mantenimiento de Software'
         },

         {
             nombre: 'Jillian Suzanne',
             edad: 21,
             claseCursa: 'Programacion 1'
         },

         {
             nombre: 'Philippe Drake',
             edad: 19,
             claseCursa: 'Metodologia de la Investigacion'
         },

         {
             nombre: 'Damon Brenton',
             edad: 27,
             claseCursa: 'Marketing'
         },

         {
             nombre: 'Dimitri Boyd',
             edad: 20,
             claseCursa: 'Calculo Diferencial'
         },

         {
             nombre: 'Alaina Salma',
             edad: 24,
             claseCursa: 'Sistemas Distribuidos'
         },

         {
             nombre: 'Gloria Tabitha',
             edad: 26,
             claseCursa: 'Filosofia'
         },

         {
             nombre: 'Irvin Darius',
             edad: 25,
             claseCursa: 'Diseno de Base de Datos'
         },

         {
             nombre: 'Valentin Elias',
             edad: 17,
             claseCursa: 'Validacion y Mantenimiento de Software'
         },

         {
             nombre: 'Joel Brenton',
             edad: 19,
             claseCursa: 'Programacion 1'
         },

         {
             nombre: 'Davina Honor',
             edad: 17,
             claseCursa: 'Metodologia de la Investigacion'
         },

         {
             nombre: 'Linus Jensen',
             edad: 24,
             claseCursa: 'Marketing'
         },

         {
             nombre: 'Leah Marcia',
             edad: 23,
             claseCursa: 'Calculo Diferencial'
         },

         {
             nombre: 'Garth Armando',
             edad: 27,
             claseCursa: 'Sistemas Distribuidos'
         },

         {
             nombre: 'Wolf Lance',
             edad: 20,
             claseCursa: 'Filosofia'
         },

         {
             nombre: 'Leticia Jeannette',
             edad: 25,
             claseCursa: 'Diseno de Base de Datos'
         },

         {
             nombre: 'Shona Pansy',
             edad: 21,
             claseCursa: 'Validacion y Mantenimiento de Software'
         },

         {
             nombre: 'Raylan Layne',
             edad: 26,
             claseCursa: 'Programacion 1'
         },

         {
             nombre: 'Al Casper',
             edad: 18,
             claseCursa: 'Metodologia de la Investigacion'
         },

         {
             nombre: 'Alvin Willem',
             edad: 22,
             claseCursa: 'Marketing'
         },

         {
             nombre: 'Shelly Kasey',
             edad: 20,
             claseCursa: 'Calculo Diferencial'
         },

         {
             nombre: 'Chrissy Viviana',
             edad: 24,
             claseCursa: 'Sistemas Distribuidos'
         },

         {
             nombre: 'Jamie Yves',
             edad: 27,
             claseCursa: 'Filosofia'
         },

         {
             nombre: 'Forrest Fide',
             edad: 26,
             claseCursa: 'Diseno de Base de Datos'
         },

         {
             nombre: 'Ali Vincent',
             edad: 21,
             claseCursa: 'Validacion y Mantenimiento de Software'
         },

         {
             nombre: 'Jet Ryland',
             edad: 18,
             claseCursa: 'Programacion 1'
         },

         {
             nombre: 'Connor Alfonso',
             edad: 19,
             claseCursa: 'Metodologia de la Investigacion'
         },

         {
             nombre: 'Kristoff Beckett',
             edad: 25,
             claseCursa: 'Marketing'
         },

         {
             nombre: 'Marlon Caesar',
             edad: 17,
             claseCursa: 'Calculo Diferencial'
         },

         {
             nombre: 'Gregor Drake',
             edad: 22,
             claseCursa: 'Sistemas Distribuidos'
         },

         {
             nombre: 'Saskia Deirdre',
             edad: 23,
             claseCursa: 'Filosofia'
         },
         {
             nombre: 'Charlene Francesca',
             edad: 20,
             claseCursa: 'Diseno de Base de Datos'
         },
         {
             nombre: 'Nihal Alden',
             edad: 21,
             claseCursa: 'Filosofia'
         },
         {
             nombre: 'Drew Drake',
             edad: 40,
             claseCursa: 'Si'
         }
     ];

     let ageRange = [ 18, 25 ];
     let output;

     output = jovenAdulto(ageRange[0], ageRange[1], alumno);
     console.log('estudiantes mayores de 18 y menores de 25 anios:\n', output );

     ageRange = 20;
     output = dosDecadas( ageRange, alumno );
     console.log('primer estudiante con edad de 20 anios: \n', output );

     ageRange = [20, 22];
     output = filtrarAlumnos( ageRange[0], ageRange[1], alumno );
     console.log('estudiantes mayores de 20 y menores de 22 anios:\n', output );
#+end_src
